### PR TITLE
[Fix] Fix parsing issue in ErrorDetail

### PR DESCRIPTION
**Pull request by costichiulan**
## Issue Description
Exceptions are not deserialized correctly, the message field contains the response JSON and the string 'Cannot construct instance of com.databricks.sdk.core.error.ErrorDetail, problem: Cannot invoke "Object.getClass()" because "m" is null'

## Changes
In ErrorDetails class, i added a null check before the unmodifiableMap is created. 

## Tests
Created an unit test in ApiErrorBodyDeserializationSuite.java

Signed-off-by: Costin Chiulan <costin.chiulan@gmail.com>

### CODE REVIEW

**Comment by costichiulan** [comment]
@mgyucht

**Review by rubensrech — APPROVED** [review]

**Comment by costichiulan** [comment]
> @costichiulan, could you update the title of your PR to `[Fix] Fix parsing issue in ErrorDetail` so that the change can properly be handled by the changelogs automation? We aim to have our PR titles phrase as imperative sentences.

Done, pushed also a new commit after executing mvn spotless:apply to pass fmt workflow

**Comment by renaudhartert-db** [comment]
> > @costichiulan, could you update the title of your PR to `[Fix] Fix parsing issue in ErrorDetail` so that the change can properly be handled by the changelogs automation? We aim to have our PR titles phrase as imperative sentences.
> 
> Done, pushed also a new commit after executing mvn spotless:apply to pass fmt workflow

Looks good, thanks! I need to double check a couple of things internally before we can proceed with merging the PR but we should be ready to go soon.

**Comment by renaudhartert-db** [comment]
Hi @costichiulan! Sorry for the delay. There's just one small last step we would need from you before proceeding with the merge. 

To contribute to this repository, we need you to sign off your PR to certify that you have the right to contribute the code and that it complies with the open source license. The rules are pretty simple, if you can certify the 
content of [DCO](https://github.com/databricks/databricks-sdk-java/blob/main/DCO), then simply add a "Signed-off-by" line to the bottom of your PR description message to certify your compliance. Please use use your real name as 
pseudonymous/anonymous contributions are not accepted.

```
Signed-off-by: Joe Smith <joe.smith@email.com>
```

Once this is done, I will approve and merge the fix. Thanks again for contributing!

**Review by renaudhartert-db — APPROVED** [review]

**Comment by renaudhartert-db** [comment]
@costichiulan, one more thing, our repository requires all [commits to be signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) for merging. Could you back sign them? Here's a [stack-overflow](https://stackoverflow.com/questions/41882919/is-there-a-way-to-gpg-sign-all-previous-commits) thread that might provide some useful pointers on how to do so:

**Comment by costichiulan** [comment]
> @costichiulan, one more thing, our repository requires all [commits to be signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) for merging. Could you back sign them? Here's a [stack-overflow](https://stackoverflow.com/questions/41882919/is-there-a-way-to-gpg-sign-all-previous-commits) thread that might provide some useful pointers on how to do so.

Done, thanks for info

**Pull request merged**
